host: http://localhost:9000/
authorization:
  server: http://localhost:5556/
  serverMetadataProxyEnabled: true
  dynamicClientRegistrationEnabled: true
dexGRPCClient:
  addr: localhost:5557
proxy:
  - path: /weather/mcp
    http:
      url: http://localhost:8000/mcp/
    webhook:
      url: http://localhost:8080/webhook/proxy/87dd8dde-c7aa-4535-a6d7-3b313ffb1d0c
    authentication:
      enabled: true
  - path: /public-weather/mcp
    http:
      url: http://localhost:8000/mcp/
    telemetry:
      enabled: true
    webhook:
      url: http://localhost:8080/webhook/proxy/323e957e-af1d-4a74-9733-b5d1fc3ae7fd
